import { GraphData } from "GraphManager/types";
// prettier-ignore
const data: GraphData = {
  nodes: [
    { id: "arithm-ops", description: "Basic Arithmetic Operations", group: 2 },
    { id: "Addition", description: "Addition", group: 2 },
    { id: "Subtraction", description: "Subtraction", group: 2 },
    { id: "Counting", description: "Counting", group: 2 },
    { id: "Numbers", description: "Numbers", group: 2 },
    { id: "Sums", description: "Sums", group: 2 },
    { id: "Product of Sequence", description: "Product of Sequence", group: 2 },
    { id: "Conditionals (math)", description: "Conditionals (math)", group: 2 },
    { id: "Multiplication", description: "Multiplication", group: 2 },
    { id: "Division", description: "Division", group: 2 },
    { id: "Modulo", description: "Modulo", group: 2 },
    { id: "Factorial", description: "Factorial", group: 2 },
    { id: "Prime Numbers", description: "Prime Numbers", group: 2 },
    { id: "Probability", description: "Probability", group: 2 },
    { id: "Conditional Probability", description: "Conditional Probability", group: 3, },
    { id: "Exponentiation", description: "Exponentiation", group: 2 },
    { id: "Logarithm", description: "Logarithm", group: 2 },
    { id: "Equation", description: "Equation", group: 2 },
    { id: "Differential Equation", description: "Differential Equation", group: 2, },
    { id: "Derivative", description: "Derivative", group: 2 },
    { id: "Functional Mathematics", description: "Functional Mathematics", group: 2, },
    { id: "Limits", description: "Limits", group: 3 },
    { id: "Functions (math)", description: "Functions (math)", group: 2 },
    { id: "Variables (math)", description: "Variables (math)", group: 2 },
    { id: "Topological Space", description: "Topological Space", group: 3 },
    { id: "neighbourhood (math)", description: "neighbourhood (math)", group: 3, },
    { id: "Fitting (linear)", description: "Fitting (linear)", group: 3 },
  ],
  links: [
    { id: "01", source: "Addition", target: "Counting", value: 10, note: "" },
    { id: "02", source: "Counting", target: "Numbers", value: 10, note: "" },
    { id: "02", source: "Multiplication", target: "Addition", value: 10, note: "", },
    { id: "03", source: "Sums", target: "Addition", value: 10, note: "" },
    { id: "b3", source: "Sums", target: "Conditionals (math)", value: 10, note: "", },
    { id: "04", source: "Product of Sequence", target: "Conditionals (math)", value: 10, note: "", },
    { id: "05", source: "Product of Sequence", target: "Sums", value: 2, note: "", },
    { id: "06", source: "Product of Sequence", target: "Multiplication", value: 10, note: "", },
    { id: "07", source: "Division", target: "Multiplication", value: 10, note: "", },
    { id: "08", source: "Modulo", target: "Division", value: 10, note: "" },
    { id: "09", source: "Division", target: "Modulo", value: 10, note: "" },
    { id: "10", source: "Prime Numbers", target: "Division", value: 10, note: "", },
    { id: "11", source: "Prime Numbers", target: "Numbers", value: 10, note: "", },
    { id: "12", source: "Factorial", target: "Multiplication", value: 10, note: "", },
    { id: "13", source: "Factorial", target: "Product of Sequence", value: 4, note: "", },
    { id: "14", source: "Factorial", target: "Addition", value: 10, note: "" },
    { id: "15", source: "Probability", target: "Division", value: 10, note: "", },
    { id: "16", source: "Probability", target: "Multiplication", value: 5, note: "", },
    { id: "17", source: "Conditional Probability", target: "Probability", value: 10, note: "", },
    { id: "18", source: "Conditional Probability", target: "Sums", value: 2, note: "", },
    { id: "19", source: "Conditional Probability", target: "Logarithm", value: 4, note: "", },
    { id: "20", source: "Conditional Probability", target: "Equation", value: 7, note: "", },
    { id: "21", source: "Exponentiation", target: "Multiplication", value: 10, note: "", },
    { id: "22", source: "Exponentiation", target: "Division", value: 10, note: "", },
    { id: "23", source: "Exponentiation", target: "Addition", value: 10, note: "", },
    { id: "24", source: "Logarithm", target: "Exponentiation", value: 10, note: "", },
    { id: "25", source: "Differential Equation", target: "Equation", value: 10, note: "", },
    { id: "26", source: "Differential Equation", target: "Derivative", value: 10, note: "", },
    { id: "27", source: "Differential Equation", target: "Functional Mathematics", value: 10, note: "", },
    { id: "28", source: "Functional Mathematics", target: "Equation", value: 10, note: "", },
    { id: "29", source: "Functional Mathematics", target: "Differential Equation", value: 2, note: "", },
    { id: "30", source: "Derivative", target: "Limits", value: 10, note: "", },
    { id: "31", source: "Limits", target: "Topological Space", value: 2, note: "", },
    { id: "32", source: "Limits", target: "neighbourhood (math)", value: 2, note: "", },
    { id: "33", source: "Limits", target: "Functions (math)", value: 8, note: "", },
    { id: "34", source: "Functions (math)", target: "Variables (math)", value: 10, note: "", },
    { id: "35", source: "Equation", target: "Variables (math)", value: 10, note: "", },
    { id: "36", source: "Fitting (linear)", target: "Functions (math)", value: 10, note: "", },
    { id: "37", source: "Fitting (linear)", target: "Sums", value: 10, note: "Least Square Regression", },
    { id: "38", source: "Fitting (linear)", target: "Exponentiation", value: 10, note: "Least Square Regression" },
    { id: "39", source: "arithm-ops", target: "Addition", value: 10, note: "" },
    { id: "40", source: "arithm-ops", target: "Subtraction", value: 10, note: "" },
    { id: "40", source: "arithm-ops", target: "Multiplication", value: 10, note: "" },
    { id: "40", source: "arithm-ops", target: "Division", value: 10, note: "" },
    { id: "15", source: "Probability", target: "arithm-ops", value: 10, note: "", },
    { id: "22", source: "Exponentiation", target: "arithm-ops", value: 10, note: "", },
  ],
};
export default data;
