import { GraphData } from "GraphManager/types";
const data: GraphData = {
  nodes: [
    { id: "Addition", group: 2 },
    { id: "Counting", group: 2 },
    { id: "Numbers", group: 2 },
    { id: "Sums", group: 2 },
    { id: "Product of Sequence", group: 2 },
    { id: "Conditionals (math)", group: 2 },
    { id: "Multiplication", group: 2 },
    { id: "Division", group: 2 },
    { id: "Modulo", group: 2 },
    { id: "Factorial", group: 2 },
    { id: "Prime Numbers", group: 2 },
    { id: "Probability", group: 2 },
    { id: "Conditional Probability", group: 3 },
    { id: "Exponentiation", group: 2 },
    { id: "Logarithm", group: 2 },
    { id: "Equation", group: 2 },
    { id: "Differential Equation", group: 2 },
    { id: "Derivative", group: 2 },
    { id: "Functional Mathematics", group: 2 },
    { id: "Limits", group: 3 },
    { id: "Functions (math)", group: 2 },
    { id: "Variables (math)", group: 2 },
    { id: "Topological Space", group: 3 },
    { id: "neighbourhood (math)", group: 3 },
    { id: "Fitting (linear)", group: 3 },
  ],
  links: [
    { source: "Addition", target: "Counting", value: 10, note: "" },
    { source: "Counting", target: "Numbers", value: 10, note: "" },
    {
      source: "Multiplication",
      target: "Addition",
      value: 10,
      note: "",
    },
    { source: "Sums", target: "Addition", value: 10, note: "" },
    {
      source: "Sums",
      target: "Conditionals (math)",
      value: 10,
      note: "",
    },
    {
      source: "Product of Sequence",
      target: "Conditionals (math)",
      value: 10,
      note: "",
    },
    {
      source: "Product of Sequence",
      target: "Sums",
      value: 2,
      note: "",
    },
    {
      source: "Product of Sequence",
      target: "Multiplication",
      value: 10,
      note: "",
    },
    {
      source: "Division",
      target: "Multiplication",
      value: 10,
      note: "",
    },
    { source: "Modulo", target: "Division", value: 10, note: "" },
    { source: "Division", target: "Modulo", value: 10, note: "" },
    {
      source: "Prime Numbers",
      target: "Division",
      value: 10,
      note: "",
    },
    { source: "Prime Numbers", target: "Numbers", value: 10, note: "" },
    {
      source: "Factorial",
      target: "Multiplication",
      value: 10,
      note: "",
    },
    {
      source: "Factorial",
      target: "Product of Sequence",
      value: 4,
      note: "",
    },
    { source: "Factorial", target: "Addition", value: 10, note: "" },
    { source: "Probability", target: "Division", value: 10, note: "" },
    {
      source: "Probability",
      target: "Multiplication",
      value: 5,
      note: "",
    },
    {
      source: "Conditional Probability",
      target: "Probability",
      value: 10,
      note: "",
    },
    {
      source: "Conditional Probability",
      target: "Sums",
      value: 2,
      note: "",
    },
    {
      source: "Conditional Probability",
      target: "Logarithm",
      value: 4,
      note: "",
    },
    {
      source: "Conditional Probability",
      target: "Equation",
      value: 7,
      note: "",
    },
    {
      source: "Exponentiation",
      target: "Multiplication",
      value: 10,
      note: "",
    },
    {
      source: "Exponentiation",
      target: "Division",
      value: 10,
      note: "",
    },
    {
      source: "Exponentiation",
      target: "Addition",
      value: 10,
      note: "",
    },
    {
      source: "Logarithm",
      target: "Exponentiation",
      value: 10,
      note: "",
    },
    {
      source: "Differential Equation",
      target: "Equation",
      value: 10,
      note: "",
    },
    {
      source: "Differential Equation",
      target: "Derivative",
      value: 10,
      note: "",
    },
    {
      source: "Differential Equation",
      target: "Functional Mathematics",
      value: 10,
      note: "",
    },
    {
      source: "Functional Mathematics",
      target: "Equation",
      value: 10,
      note: "",
    },
    {
      source: "Functional Mathematics",
      target: "Differential Equation",
      value: 2,
      note: "",
    },
    { source: "Derivative", target: "Limits", value: 10, note: "" },
    {
      source: "Limits",
      target: "Topological Space",
      value: 2,
      note: "",
    },
    {
      source: "Limits",
      target: "neighbourhood (math)",
      value: 2,
      note: "",
    },
    {
      source: "Limits",
      target: "Functions (math)",
      value: 8,
      note: "",
    },
    {
      source: "Functions (math)",
      target: "Variables (math)",
      value: 10,
      note: "",
    },
    {
      source: "Equation",
      target: "Variables (math)",
      value: 10,
      note: "",
    },
    {
      source: "Fitting (linear)",
      target: "Functions (math)",
      value: 10,
      note: "",
    },
    {
      source: "Fitting (linear)",
      target: "Sums",
      value: 10,
      note: "Least Square Regression",
    },
    {
      source: "Fitting (linear)",
      target: "Exponentiation",
      value: 10,
      note: "Least Square Regression",
    },
  ],
};
export default data;
