services:
  # development
  frontend:
    image: node:20.10.0
    ports:
      - "3000:5173" # host:container
    networks:
      - learngraphnet
    environment:
      REACT_APP_BACKEND_DN: "http://localhost:3000/query"
      # for mobile device testing you'll want you dev box's ip here
      #REACT_APP_BACKEND_DN: "http://192.168.0.78:3000/query"
    volumes:
      - type: bind
        source: ./
        target: /src
    working_dir: /src
    command: npm run devPublic
  # production test, see `npm run build-arm/-amd`
  #frontend:
  #  image: test-frontend
  #  networks:
  #    - learngraphnet
  #  ports:
  #    - "3000:80" # host:container
  #  environment:
  #    REACT_APP_BACKEND_DN: "https://learngraph.org/query"
  #    VITE_POSTHOG_API_KEY: "${VITE_POSTHOG_API_KEY}"
  #    VITE_POSTHOG_HOST: "${VITE_POSTHOG_HOST}"
  #    VITE_SLACK_WEBHOOK_TOKEN: "${VITE_SLACK_WEBHOOK_TOKEN}"
networks:
  learngraphnet:
    name: learngraphnet
    external: true
