services:
  frontend:
    image: node:20.10.0
    ports:
      - "3000:5173" # host:container
    networks:
      - learngraphnet
    environment:
      REACT_APP_BACKEND_DN: "http://localhost:3000/query"
      # for mobile device testing you'll want you dev box's ip here
      #REACT_APP_BACKEND_DN: "http://192.168.0.78:3000/query"
    volumes:
      - type: bind
        source: ./
        target: /src
    working_dir: /src
    command: npm run devPublic
networks:
  learngraphnet:
    name: learngraphnet
    external: true
