services:
  frontend:
    image: node:20.10.0
    ports:
      - "3000:5173" # host:container
    networks:
      - learngraphnet
    environment:
      REACT_APP_BACKEND_DN: "http://prototype.learngraph.org/query"
    volumes:
      - type: bind
        source: ./
        target: /src
    working_dir: /src
    command: npm run devPublic
networks:
  learngraphnet:
    name: learngraphnet
    external: true
