const {
  VITE_POSTHOG_HOST: POSTHOG_HOST,
  VITE_POSTHOG_API_KEY: POSTHOG_API_KEY,
  VITE_SLACK_WEBHOOK_TOKEN: SLACK_WEBHOOK_TOKEN,
} = import.meta.env;

export { POSTHOG_API_KEY, POSTHOG_HOST, SLACK_WEBHOOK_TOKEN };
